name: weather
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  animation_search_bar: ^0.0.10
  shared_preferences: ^2.0.17
  intl: ^0.18.0
  gradient_borders: ^1.0.0
  weather_animation: ^0.0.2
  location: ^4.4.0
  lottie: ^2.2.0
  cupertino_listview: ^2.0.0
  smooth_page_indicator: ^1.0.1
  carousel_slider: ^4.2.1
  sleek_circular_slider: ^2.0.1
  smooth_compass: ^2.0.4
  arrow_path: ^3.0.0
  weather_icons: ^3.0.0
  palette_generator: ^0.3.3+2
  adv_flutter_weather: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0


flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/images.png"